apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solana-transactions

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

images:
  - name: us-central1-docker.pkg.dev/aiservice-solana-transactions/solana-transactions/be
    newName: us-central1-docker.pkg.dev/aiservice-solana-transactions/solana-transactions/be
    newTag: latest
  - name: us-central1-docker.pkg.dev/aiservice-solana-transactions/solana-transactions/fe
    newName: us-central1-docker.pkg.dev/aiservice-solana-transactions/solana-transactions/fe
    newTag: latest
